#!/usr/bin/env python3
"""Measures how completely the tests cover HCL.

    python3 tools/coverage.py rules          # rules per area, and rules without tests
    python3 tools/coverage.py spec           # rules and tests per spec section
    python3 tools/coverage.py go [--functions]
                                             # code of hashicorp/hcl exercised by the tests
    python3 tools/coverage.py disputes       # disputed tests by spec section, as Markdown
    python3 tools/coverage.py anchors <dir>  # regenerate tools/spec-anchors.txt from a
                                             # checkout of the spec documents

The "go" command needs Go. It builds the reference adapter with coverage
instrumentation and runs every test through it.
"""

import argparse
import json
import os
import re
import subprocess
import sys
import tempfile
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SPEC_DOCS = ("spec.md", "hclsyntax/spec.md", "json/spec.md", "ext/typeexpr/README.md", "ext/customdecode/README.md",
             "ext/tryfunc/README.md", "ext/userfunc/README.md", "ext/dynblock/README.md")
COVER_PACKAGES = [
    "./...",  # Go only writes coverage data if the main package is instrumented too
    "github.com/hashicorp/hcl/v2",
    "github.com/hashicorp/hcl/v2/hclsyntax",
    "github.com/hashicorp/hcl/v2/json",
    "github.com/hashicorp/hcl/v2/ext/customdecode",
    "github.com/hashicorp/hcl/v2/ext/typeexpr",
    "github.com/zclconf/go-cty/cty",
    "github.com/zclconf/go-cty/cty/convert",
    "github.com/zclconf/go-cty/cty/function",
]


def load_rules():
    rules = []
    for path in sorted((ROOT / "coverage").glob("*.json")):
        data = json.loads(path.read_text(encoding="utf-8"))
        for rule in data["rules"]:
            rules.append(dict(rule, area=data["area"]))
    return rules


def load_tests():
    tests = {}
    for path in sorted((ROOT / "tests").rglob("test.json")):
        tests[path.parent.relative_to(ROOT / "tests").as_posix()] = json.loads(path.read_text(encoding="utf-8"))
    return tests


def cmd_rules(_args):
    by_area = defaultdict(lambda: [0, 0, 0])
    for rule in load_rules():
        counts = by_area[rule["area"]]
        counts[0] += 1
        counts[1 if "tests" in rule else 2] += 1
    tests = load_tests()
    tests_by_area = defaultdict(int)
    for name in tests:
        tests_by_area["/".join(name.split("/")[:2])] += 1
    width = max((len(a) for a in set(by_area) | set(tests_by_area)), default=4)
    print(f"{'area':<{width}}  {'tests':>5}  {'rules':>5}  {'tested':>6}  {'untested':>8}")
    for area in sorted(set(by_area) | set(tests_by_area)):
        rules, tested, untested = by_area[area]
        print(f"{area:<{width}}  {tests_by_area[area]:>5}  {rules:>5}  {tested:>6}  {untested:>8}")
    totals = [sum(c[i] for c in by_area.values()) for i in range(3)]
    print(f"{'total':<{width}}  {len(tests):>5}  {totals[0]:>5}  {totals[1]:>6}  {totals[2]:>8}")
    untested = [r for r in load_rules() if "untested" in r]
    if untested:
        print("\nRules without tests:")
        for rule in untested:
            print(f"  {rule['id']}: {rule['untested']}")


def cmd_spec(_args):
    anchors = [line for line in (ROOT / "tools" / "spec-anchors.txt").read_text().splitlines()
               if line and not line.startswith("#")]
    rules, tests = defaultdict(int), defaultdict(int)
    for rule in load_rules():
        rules[rule["spec"]] += 1
    for meta in load_tests().values():
        for anchor in meta.get("spec", []):
            tests[anchor] += 1
    width = max(len(a) for a in anchors)
    print(f"{'spec section':<{width}}  {'rules':>5}  {'tests':>5}")
    for anchor in anchors:
        marker = "" if rules[anchor] or tests[anchor] else "  <- nothing yet"
        print(f"{anchor:<{width}}  {rules[anchor]:>5}  {tests[anchor]:>5}{marker}")


def cmd_disputes(_args):
    by_anchor = defaultdict(list)
    for name, meta in load_tests().items():
        if meta.get("status") == "disputed":
            by_anchor[meta["spec"][0]].append((name, meta))
    total = sum(len(tests) for tests in by_anchor.values())
    print(f"# Disputed tests\n\n{total} tests where the spec and hashicorp/hcl v2.24.0 disagree, or the spec "
          "doesn't decide. Each follows hashicorp/hcl. Generated by `python3 tools/coverage.py disputes`.\n")
    anchors = [line for line in (ROOT / "tools" / "spec-anchors.txt").read_text().splitlines()
               if line and not line.startswith("#")]
    for anchor in sorted(by_anchor, key=lambda a: anchors.index(a) if a in anchors else len(anchors)):
        print(f"## [{anchor}](https://github.com/hashicorp/hcl/blob/v2.24.0/{anchor})\n")
        for name, meta in sorted(by_anchor[anchor]):
            print(f"- **{name}**: {meta['description']}.")
            print(f"  {meta['notes']}")
        print()


def cmd_go(args):
    adapter_dir = ROOT / "adapters" / "go"
    with tempfile.TemporaryDirectory(prefix="hcl-coverage-") as tmp:
        tmp = Path(tmp)
        binary, data = tmp / "hcl-go-adapter", tmp / "data"
        data.mkdir()
        run(["go", "build", "-cover", "-coverpkg=" + ",".join(COVER_PACKAGES), "-o", str(binary), "."], cwd=adapter_dir)
        env_run([sys.executable, str(ROOT / "runner" / "hcltest.py"), "--adapter", str(binary)], {"GOCOVERDIR": str(data)})
        print(run(["go", "tool", "covdata", "percent", "-i", str(data)], cwd=adapter_dir), end="")
        if args.functions:
            profile = tmp / "profile.txt"
            run(["go", "tool", "covdata", "textfmt", "-i", str(data), "-o", str(profile)], cwd=adapter_dir)
            # The scanner is generated from Ragel (.rl) files, which "go tool cover"
            # can't read, so leave those lines out.
            lines = profile.read_text().splitlines(keepends=True)
            profile.write_text("".join(line for line in lines if ".rl:" not in line))
            report = run(["go", "tool", "cover", "-func", str(profile)], cwd=adapter_dir)
            for package in ("hclsyntax", "json", "ext/typeexpr"):
                print(f"\n{package} functions below 100%:")
                for line in report.splitlines():
                    if f"/v2/{package}/" in line and not line.rstrip().endswith("100.0%"):
                        print("  " + re.sub(rf"^.*/v2/{package}/", "", line))


def cmd_anchors(args):
    anchors = []
    for doc in SPEC_DOCS:
        seen, in_code = {}, False
        for line in (Path(args.spec_dir) / doc).read_text(encoding="utf-8").splitlines():
            if line.startswith("```"):
                in_code = not in_code
            match = None if in_code else re.match(r"^#{1,6}\s+(.*)$", line)
            if not match:
                continue
            # The same rules GitHub uses to turn headings into link anchors.
            title = re.sub(r"[_*`]", "", match.group(1)).strip().lower()
            slug = re.sub(r"[^\w\- ]", "", title).replace(" ", "-")
            count = seen.get(slug, 0)
            seen[slug] = count + 1
            anchors.append(f"{doc}#{slug}" + (f"-{count}" if count else ""))
    header = ("# Section anchors in the HCL spec and the READMEs of its extensions at hashicorp/hcl v2.24.0.\n"
              "# Tests and coverage files may only link to these.\n"
              "# Regenerate with: python3 tools/coverage.py anchors <spec-dir>\n")
    (ROOT / "tools" / "spec-anchors.txt").write_text(header + "\n".join(anchors) + "\n", encoding="utf-8")
    print(f"wrote {len(anchors)} anchors")


def run(command, cwd=None):
    return subprocess.run(command, cwd=cwd, check=True, capture_output=True, text=True).stdout


def env_run(command, extra_env):
    subprocess.run(command, check=False, env=dict(os.environ, **extra_env), stdout=subprocess.DEVNULL)


def main():
    parser = argparse.ArgumentParser(description="Measure test coverage of HCL.")
    commands = parser.add_subparsers(dest="command", required=True)
    commands.add_parser("rules", help="rules per area, and rules without tests").set_defaults(func=cmd_rules)
    commands.add_parser("spec", help="rules and tests per spec section").set_defaults(func=cmd_spec)
    commands.add_parser("disputes", help="disputed tests by spec section, as Markdown").set_defaults(func=cmd_disputes)
    go = commands.add_parser("go", help="code of hashicorp/hcl exercised by the tests")
    go.add_argument("--functions", action="store_true",
                    help="list hclsyntax, json and ext/typeexpr functions that aren't fully covered")
    go.set_defaults(func=cmd_go)
    anchors = commands.add_parser("anchors", help="regenerate tools/spec-anchors.txt")
    anchors.add_argument("spec_dir", help="a checkout of hashicorp/hcl v2.24.0, which has the spec documents")
    anchors.set_defaults(func=cmd_anchors)
    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
